uktrade/pg-bulk-ingest

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
> Add replace function

- pg_bulk_ingest.py
The logic of multiple tables isn't quite done, so no test on this, but a step towards it
> fix: skipping of rows not on first table

- pg_bulk_ingest.py
It's a tiny little bit more functional/pure/referentially transparent
> refactor: generator expression over generator function

- README.md
- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
The various cases will need to be manually controlled for the same "pipeline", and suspect it's easier if it's via options to a single function
> feat: combine the 3 functions into one "ingest" function

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
Just to be a touch more future friendly
> feat: use mode enum-ish rather than boolean

- pg_bulk_ingest.py
It's ignored for now, so it's mostly to see how it feels
> feat: add visibility argument

- README.md
Since for now only supporting a single table
> docs: remove mention of tables in favour or singular table

- test_pg_bulk_ingest.py
And testing of when batches become visible
> test: better separation of test cases

- README.md
- pg_bulk_ingest.py
This is a bit "stringly-typed" but it means that configuration can more easily come from outside the code.
> feat: use string-based constants

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
If there is any index change, this migrates the entire table to a new table. This could be optimised - for example dropping an index could be done on the existing table. Leaving such optimisations to further work.
> feat: add/remove indexes as part of migration

- README.md
- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
This is primarily for client code to be able to update metadata for each batch
> feat: callback function before batch is visible

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
This fixes two bugs with long column names, due to how SQLAlchemy then chooses index names for such columns.
- Fixes attempting to create an index with the name of an index that already exists.
- Repeatedly migrating the same table
> fix: bugs with indexes when column names are long

- .github/workflows/publish-pypi.yml
The .yml file wasn't in the right structure. And realising that the extraction of the tag name has to be done before the build
> fix: publishing to PyPI

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
The name that SQLAlchemy constructs for indexes isn't unique enough, especially for multi-column indexes, and so would cause errors when migrating since it would try to create multiple indexes with the same name
> fix: multi-column indexes that share columns, and fix loss of nullable on migration

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
When there is primary key and if there are duplicates within a batch, it fails to insert data into the batch table with `UniqueViolation` error. 
Fix was to disable primary key on the batch table, let all the data in and then deduplicate before attempting upsert into the target table.
> fix: remove duplicates in a batch before upsert

- README.md
Clarify things and also document HighWatermark.EARLIEST
> docs: improve documentation on the HighWatermark class

- pg_bulk_ingest.py
It looks like PostgreSQL SELECT permissions follow renames. So we can grant permissions before the drop/rename that's part of a migration that uses a migration table
> feat: avoid any possible race condition by granting permissions earlier

- pg_bulk_ingest.py
- test_pg_bulk_ingest.py
The purpose of this is primarily to better support ingests that can't be done in batches - where there is a single batch with `delete=Deleta.BEFORE_FIRST_BATCH`. In this case, the data sizes can be large, and so it's more performant to create indexes after data has been ingested into the table.
To keep logic simple, now a migration on column or index changes is always via a separate ingest table. Maybe down the line we can re-introduce the optimisation to not migrate via a separate table, but there are so many cases for which it can't be done, it feels safer to always do it.
This has a secondary effect reflected in tests - now changes are never visible into before the first batch. Before, in the case of migrations, some migration-behaviour _was_ visible. The price of this however is that …
> feat: if deleting, ingest into fresh table rather than actually deleting data

- pg_bulk_ingest.py
Add `_tmp_` to names assigned to tables and indexes so as to make it explicit that these are temporary relations.
This should allow them to be more easily excluded when listing all tables in a database, for example [here](https://github.com/uktrade/data-workspace/blob/master/dataworkspace/dataworkspace/apps/explorer/schema.py#L105) in Data Workspace
> adding _temp to relation names

- docs/ingesting-data-with-airflow.md
Adding documentation for how to ingest data using pg-bulk-ingest
> docs: add docs for ingesting data

- docs/airflow.md
This is because Airflow docs talks of DAGs
> docs: use DAG more the pipeline when talking about Airflow

- test_pg_bulk_ingest.py
The private function to_file_like_obj didn't have full code coverage. This _should_ test it better.
> tests: test for larger amounts of data

- package-lock.json
This build package-lock.json via npm install again. I'm not convinced it gives a stable output...
> build(deps): fix package-lock.json for the third time

- docs/high-watermark.md
Hopefully it covers more cases/gotchas now
> docs: flesh out high-watermarks page

- docs/high-watermark.md
(Thank you to the reporter :-))
> docs: fix more reported typos

- package-lock.json
- package.json
Re-install the dependencies for the documentation
- Deleting package-lock.json
- Remove force resolutions from package.json
- npm install --omit=dev
> build: omit dev dependencies for docs

- package-lock.json
- package.json
And update packages. Triggered by other docs sites taking many hours to do `npm ci`. It didn't on this one for some reason, but doing this for consistency.
> build(deps): simplify package.json

- package-lock.json
> build(deps): update various documentation deps

- .github/workflows/test.yml
- pg_bulk_ingest/__init__.py
- pyproject.toml
- test_pg_bulk_ingest.py
* Adding type annotations to the [pg-bulk-ingest](https://github.com/uktrade/pg-bulk-ingest) lib
* Including it on the CI pipeline checks
* Making it compatible for python >= 3.7
> feat: enable-type-checking-in-repo

- pg_bulk_ingest/__init__.py
- test_pg_bulk_ingest.py
This makes sure that in the case of materialized views appearing in multiple depths of the graph of dependencies of a table, they are recreated in the correct order.
> fix: graphs of materialized views where views are repeated

- pg_bulk_ingest/__init__.py
- test_pg_bulk_ingest.py
This change drops use of information_schema.table_privileges to find what roles have SELECT privileges, and replaces it with using pg_class directly. This fixes the issue where roles that do not also have USAGE on the table's schema end up with privileges lost after an ingest that ingests into a new table (e.g. after DELETE_BEFORE_FIRST_BATCH).
The issue was essentially caused by the fact that information_schema.table_privileges seems to only include table privileges for roles that have USAGE on the table's schema.
This is particularly an issue for systems that use https://github.com/uktrade/pg-sync-roles, e.g. https://github.com/uktrade/data-workspace-frontend, because SELECT and USAGE are typically granted on different roles.
By using pg_class directly This is also more performant - …
> fix: preserve SELECT for roles that don't have USAGE

- pg_bulk_ingest/__init__.py
- test_pg_bulk_ingest.py
If views (including materialized) views are recreated, this change preserves SELECT permissions roles had on them before they were recreated.
> feat: preserve SELECT on views

- pg_bulk_ingest/__init__.py
- test_pg_bulk_ingest.py
This fixes the re-creation of views on tables that have commas in their column names. This is done my moving the column deduplication code (which split on commas, and incorrectly if they were in the middle of a column name), into the query that fetches view definitions
> fix: commas in columns names with views

- pg_bulk_ingest/__init__.py
It's big enough I think to stand alone - it can use longer lines if not indented for example
> refactor: move views SQL to top level

- .github/workflows/deploy-package-to-pypi.yml
> ci: update version of upload action

- pg_bulk_ingest/__init__.py
This makes is so the as_string function, used to convert sql.SQL instances to strings, can be defined per dialect.
This is to more easily support _other_ dialects, and specifically an ADBC dialect that will have a slightly different as_string function.
Along the way, also changeing the ingest functon to not pass around variables that are constant since close to the beginning of the ingest function to cut noise. The exception is the insert_rows function, because this might end up overwritable by client code, and I think it would be good to have the connection passed to it.
> refactor: per-dialect as_string
