uktrade/pg-bulk-ingest

test_pg_bulk_ingest.py

This is since psycopg2 works in both SQLAlchemy 1 and 2

test: prefer psycopg2 than 3

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

Counter-intuitively, the table and schema names have to be quoted as literals before going into the SQL, and then quoted as identifiers only inside PostgreSQL itself.

fix: when have special characters in table names

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

Suspect that adding a column holds an access exclusive lock on the table, even though it doesn't re-write the entire table. So, to avoid ingest holding this lock during a batch, the migrations have to be committed, and so have to then be visible before the first batch.
Other visibility behaviour is possible - for example always ingesting into a migration table and swapping with the live at the end. But this would require a copy of all data in all migration circumstances.

fix: long-running table lock if there is a migration

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

The longer term plan is to have at least one option for visibility - after all batches - so the same callback could be used then

feat: rename on_before_batch_visible to on_before_visible

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

As well as being able to set high watermark to 'LATEST', now it can be set to 'EARLIEST' which is a constant of None, re-running the pipeline from the start.

feat: High watermark can now be assigned to earliest

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

This is done to try to increase speed in some cases - it is suspected that the upsert, using INSERT .. . ON CONFLICT DO UPDATE may be slow

feat: addition of an upsert mode that disables upsert even if there is a primary key

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

SQLAlchemy chooses the same index name when multi column indexes start with the same column, which means initial table creation fails. To avoid this, we don't create indexes when initially creating the table, and leave them to the migration code, which gives the indexes random names

fix: errors due to indexes already existing when creating table

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

This is to make it consistent with the regular upsert-behaviour - most recent row wins.

feat: when de-duplicating choose the most recent row

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

This converts the Delete.ALL to Delete.BEFORE_FIRST_BATCH. In the case of there being batches ingested, the behaviour is identical. In the case of there being no batches, no data is deleted. This is helpful for the cases where each batch contains the entire dataset but if no batches after high watermark, we want to leave the data alone.

feat: delete before first batch

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

The dropping of the table means permissions are lost, so we have to manually query them before the drop, and re-set them afterwards.

feat: preserve SELECT permissions when a migration went via another table

---

README.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

This is to support future changes where the table ingested into might not be the target table.

feat: pass schema and table to on before visible

---

.github/workflows/deploy-package-to-pypi.yml
.github/workflows/test.yml

This avoids errors like
Error: Can't use 'tar -xzf' extract archive file:
/home/runner/work/_actions/_temp_575ca616-4abd-4ab1-8b7a-7cfa8cba3133/3728ca6e-c608-40ab-85d1-432455aec994.tar.gz. return code: 2.

ci: use latest checkout action to avoid errors

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

In the case of no batches, which can happen if there is logic based on high watermark to not ingest, then an empty table was being created and committed, and so forever visible to other database users.
This change makes it so the table is only created if there is a batch.

fix: only create a table to ingest into if there is at least one batch

---

pg_bulk_ingest.py

Passing table and schema name through "str" seems to fix errors in Airflow
> Unable to redact 'Unable to redact %r, please report this via <https://github.com/apache/***/issues>. Error was: %s: %s', please report this via <https://github.com/apache/***/issues>. Error was: RecursionError: maximum recursion depth exceeded in __instancecheck_
Have to admit, not sure why

fix: infinite recursion error when logging from Airflow

---

pg_bulk_ingest.py

Commenting it out as a form of documentation to explain why it's not needed, as well to avoid a gotcha in case someone decided to copy and paste the to_file_like_obj code elsewhere

refactor: comment out dead code (but don't remove it)

---

package-lock.json

This copies the package-lock.json from stream-zip (changing the package name) in an effort to avoid https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
Not really sure why this had to be done - the package.json file is identical with stream-zip's, so npm install of it should result of the same lock file. But somehow it doesn't. Judging it not worth it to find out.

build(deps): avoid axios vulnrability (again)

---

pg_bulk_ingest.py
pyproject.toml

This now uses the code in https://github.com/uktrade/to-file-like-obj rather than having a copy of it.
This is to reduce overal duplication of code in many uses of pg-bulk-ingest, because https://github.com/uktrade/to-file-like-obj will be used anywhere (because for example it's used in the robust stream-parsing of CSVs)

refactor: use to-file-like-obj

---

docs/api.md
docs/get-started.md
docs/index.md
docs/under-the-hood.md
pg_bulk_ingest.py
test_pg_bulk_ingest.py

This adds support for ingesting to multiple tables in a single call to the ingest function.
This works by having buffering incoming data, up to a maximum of 10k rows per table. But it does it in a slightly fancy way, where
- The data is still streamed in for the first table using COPY FROM - it doesn't wait for a buffer to be filled.
- But during this, rows that appear in the stream for other tables are buffered.
- If a buffer hits 10k rows then the first COPY FROM is ended, and a new one begun, starting off with an empty of its 10k buffer, but then continues in a streaming way. And this one continues until the next table fills its buffer, and so on.
This means that the behaviour for a single table is exactly as now: no buffer is used because it's all streamed straight in in a single COPY …

feat: support multiple tables

---

README.md

Now multiple tables are supported, so it's slightly misleading to always talk about the one table.

docs: avoid hinting that only a single table is supported

---

package-lock.json
package.json

Without this I don't think the docs build in GitHub actions

build(deps): restore rollup-linux-x64-gnu for building docs

---

pg_bulk_ingest.py

Copying the SELECT permissions on each batch is semantically fine, but
- Unnecessary at best
- And at worst, can cause hanging and "tuple concurrently updated" errors when other clients try to do GRANT SELECT on the tables in question
This change makes it so the copy of SELECT privileges only happens when we ingest the first batch into a new table, and never otherwise.
There is an existing test  test_migrate_add_column_not_at_end_permissions_preserved that test permissions are preserved.

feat: only GRANT when ingesting into a new table

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

This reduces the number of queries run when copying existing SELECT privileges, which happens at the end of the first batch in the cases when the ingest is not directly into the live table.
The existing test that privileges are preserved is extended to make sure the `','.join(...` behaviour is correct

perf: GRANT all SELECT privileges in a single query

---

pg_bulk_ingest.py

In some cases people think pg-bulk-ingest is either doing nothing during ingest, or loading all the data into memory. Adding in a bit more logging to make it clearer data is going into the database, including interleaved with fetching data from source (due to the magic of iterables/generators).
The complex logic on when to log is an attempt to make the logging suitable for both small and large numbers of rows without per ingest configuration, and keeping the noise down in the logs. It logs every 100 rows initially, going up to logging every million rows later in the ingest. For example it could log:
Ingesting from source into the database...
Ingested 100 rows...
Ingested 200 rows...
Ingested 300 rows...
Ingested 400 rows...
Ingested 500 rows...
Ingested 600 rows...
Ingested 700 rows... …

 feat: logging during ingest

---

pg_bulk_ingest.py
test_pg_bulk_ingest.py

Issue identified when a single batch of data is ingested to multiple SQL tables, the high watermark is not written to the correct table (the first in the list of target tables) in order to be used in subsequent DAG runs. This is amended by using the schema and table variables as defined in the save_comment method. A test for this (test_multiple_tables_high_watermark) can be found in the test script.

fix: save_comment method to use passed table variables

---

docs/airflow.md

to clarify sync's hwm arg (setting) is not the same as batches' hwm arg (value)

feat: airflow get started to separate hwm settings and hwm value

---

.github/workflows/test.yml
docs/compatibility.md

This:
- Drops support for Python 3.7
- Moves to using uv for installing Python versions rather than the setup-python action
- Adds Python 3.12 to tests in CI
The drop of Python support is because neither GitHub's setup-python action nor uv now support Python 3.7. The move to uv is because it seems to support the install of more Python versions that GitHub setup-python action.

feat: drop support for Python 3.7

---

.github/workflows/test.yml
Dockerfile
pyproject.toml
start-services.sh
stop-services.sh
test_pg_bulk_ingest.py

This adds a test to ensure pg-bulk-ingest can deal with pgvector types, and changes some of the associated files relating to automating testing so that these tests can be run with multiple versions of postgres and pgvector

test: add tests for vector types

---

.github/workflows/deploy-docs-to-github-pages.yml

This fixes the GitHub pages documentation deployment by bumping the version of actions/upload-pages-artifact to v3 (v2 no longer functions)

fix: doc deployment

---

.github/workflows/test.yml

The changes how code coverage is uploaded to Codecov - now using a token.
This is because without using a token frequently hit rate limiting, and this should be much less likely if using our own token.
The token was added as a "repository secret" before this change was raised.

ci: use token to upload code coverage

---

.github/workflows/deploy-docs-to-github-pages.yml

This is a second attempt at fixing the upload of docs to GitHub pages. This time, by bumping the version of actions/deploy-pages to the most recent - hopefully it can now find the artifact uploaded by actions/upload-pages-artifact

fix: upload of docs to GitHub pages (attempt 2)

---

pg_bulk_ingest/__init__.py
test_pg_bulk_ingest.py

Refactoring files to apply consistency to have two blank lines between top-level functions, as per [PEP-8](https://peps.python.org/pep-0008/#blank-lines)

apply consistent two blank lines between top-level functions

---

.github/workflows/test.yml
docs/compatibility.md
pyproject.toml
test_pg_bulk_ingest.py

This re-introduces support for Python 3.7, albeit Python 3.7.7. This is done by pinning to an earlier version of uv, one that still can install this version of Python.

feat: re-introduce support for Python 3.7.7

---

.github/workflows/test.yml
docs/compatibility.md
pyproject.toml

This makes tests run on Python 3.13.
psycopg2 doesn't support Python 3.13.0 until 2.9.10, so tests for Python 3.13.0 are not run for earlier psycopg2
Similarly, SQLAlchemy 2 doesn't support Python 3.13.0 until 2.0.31.

ci: run tests on Python 3.13

---

pg_bulk_ingest/__init__.py
pytest.ini
test_pg_bulk_ingest.py

* added support for tables with dependent views during table ingestions
* view definitions are recreated exactly as-is
* view dependency sql with parsimonious joins
* order agnostic two-phase views recreation: create dummy views with correct structure, replace all views with their actual definitions
* ingestions would fail if a table had dependent views
* now you can safely modify table schemas even when views depend on them
* simple dependent views
* multiple views on single table 
* cascading views (views depending on other views)
* simple cyclic views (2 views)
* complex cyclic dependencies (3+ views)
* views with complex expressions including:
* window functions
* CASE expressions
* recursive CTEs
* multiple CTEs and self-joins
* nested subqueries
* cross-view dependencies
* …

feat: make pg-bulk-ingest views compatible

---

pg_bulk_ingest/__init__.py
start-services.sh
test_pg_bulk_ingest.py

This removes commits per view when recreating views, and restoring a commit once per batch approach, so changes are only seen by other clients at the end of a batch and not before.
This does mean the exclusive locks on all the views are accumulated, but I think that is the least-bad option, because otherwise views will be visible in an inconsistent state (/ without any data in some cases), albeit briefly.

fix: only commit once per batch, even when recreating views

---

pg_bulk_ingest/__init__.py
test_pg_bulk_ingest.py

This adds an ORDER BY clause to the view discovery query to make sure views are returned in order of their dependency.
This is for materialised views, so they are created, and so refreshed, in order.

fix: improve robustness of chains of materialized views

---

docs/under-the-hood.md

This makes sure that the docs mention that views get recreated in the cases of tables being replaced.

docs: mention views being recreated

---

pg_bulk_ingest/__init__.py
test_pg_bulk_ingest.py

This adds in the use of `acldefault` when finding existing SELECT privileges on a view. This is so that SELECT privileges are not lost when views owned by users other than doing the ingest are recreated.
Suspect this is still another change after this - to make sure ownership of recreated views are preserved.

fix: preservation of SELECT on views by view owner

---

.github/workflows/test.yml
pyproject.toml
test_pg_bulk_ingest.py

This refactors tests, including how they are run in ci, and specifically:
- The engine type (aka dialect) is chosen by parameterisation, rather than what happens to be installed
- The versions installed are wherever possible enshrined in pyproject.toml via constraints on the python_version
This is done primarily to make it easier to test with more dialects (e.g. with an ADBC dialect to ingest arrow table more efficiently), but it also makes the ci config more understandable without the many excludes.

refactor: test multiple engine types/dialects each test run via parameterisation

---

pg_bulk_ingest/__init__.py

This moves the injection of the type of csv copy from stdin i.e. the one of psycopg2 or the one for psycopg3, earlier in the processing, so core code of ingestion doesn't need to pass any copy_from_stdin function.
This is a step towards allowing more way of ingesting data, and specifically ones that don't need a copy from stdin function passed to them (for example ingesting Arrow tables via an ADBC SQLAlchemy dialect).
This also tightens up what happens if modules are not installed but attempted to be used - a KeyError should be raised right at the beginning of the ingest, rather than attempted to use something that's None later (the KeyError could be surfaced as a nicer error in future changes). This also groups the psycopg2/psycopg related code closer together in the source file.

refactor: move injection of csv copy from stdin to earlier in processing
